import Head from 'next/head'
import { Inter } from '@next/font/google'

// Components
import Topnav from '../components/header/topnav'
import SideNav from '../components/sidenav'
import Footer from '../components/footer'
import Admin from '../components/admin'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Teck-App - Admin</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <main className='color-s'>
        <Topnav />
        <div className='flex'>
          <SideNav />
          <Admin/>
          <Admin/>
        </div>
        <Footer/>
      </main>
    </>
  )
}
