import Head from 'next/head'
import { Inter } from '@next/font/google'
import Topnav from '../components/topnav'
import SideNav from '../components/sidenav'


const inter = Inter({ subsets: ['latin'] })

export default function maintenence() {
  return (
    <>
      <Head>
        <title>Teck-App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className='color-s'>
        <Topnav />
        <div className='flex'>
          <SideNav />

          <div className='flex'>
            <Form />
            <Notification />
          </div>
        </div>
      </main>
    </>
  )
}

function Form() {
  return (
    <>
      <div className="m-5 rounded-md w-96 h-96 bg-slate-300">Form</div>
    </>
  )
}


function Notification() {
  return (
    <>
      <div className='m-5 rounded-md w-70 h-96 bg-slate-300'>Notification Centre</div>
    </>
  )
}