import Head from 'next/head'
import { Inter } from '@next/font/google'
import { useEffect, useState } from "react";

// Components
import Topnav from '../components/Topnav'
import SideNav from '../components/Sidenav'
import Vehiclecard from '../components/vehicle-cards/Vehiclecard'
import Vehiclecard1 from '../components/vehicle-cards/Vehiclecard1'
import Vehiclecard2 from '../components/vehicle-cards/Vehiclecard2'
import Vehiclecard3 from '../components/vehicle-cards/Vehiclecard3'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  
  return (
    <>
      <Head>
        <title>Teck-App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className='color-s'>
        <Topnav />
        <div className='flex'>
          <SideNav />
          <div className='flex items-end mx-auto my-6'>
            <Vehiclecard />
            <Vehiclecard1 />
            <Vehiclecard2 />
          </div>
        </div>
        <div className='flex justify-end'>
          <div className='flex items-end mx-auto mr-8'>
            <Vehiclecard3 />
            <Vehiclecard2 />
            <Vehiclecard />
          </div>
        </div>
      </main>
    </>
  )
}
