# Generated by Django 4.1.5 on 2023-01-08 05:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Truck',
            fields=[
                ('truck_id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('truck_type_id', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='TruckSensorData',
            fields=[
                ('log_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('time_stamp', models.DateTimeField()),
                ('gps_northing', models.FloatField(blank=True, null=True)),
                ('gps_easting', models.FloatField(blank=True, null=True)),
                ('gps_elevation', models.FloatField(blank=True, null=True)),
                ('fuel_rate', models.FloatField(blank=True, null=True)),
                ('status', models.CharField(max_length=255)),
                ('payload', models.FloatField(blank=True, null=True)),
                ('truck_type_id', models.PositiveIntegerField()),
                ('shovel_id', models.PositiveIntegerField()),
                ('dump_id', models.PositiveIntegerField()),
                ('rnd', models.PositiveIntegerField()),
                ('truck', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='trucker', to='playground.truck')),
            ],
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('truck', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='truck', to='playground.truck')),
            ],
        ),
    ]
